### ISSUE TITLE
Updating from 0.1.0.b1 to 0.1.0

### ISSUE THREAD

**Issue by EricThomson** [nel-lab/mesmerize-core#161]
On Windows machine.

I have a virtual env with version 0.1.0.b1 and am trying to upgrade to 0.1.0 without creating a brand new virtual environment. 

I tried `mamba update mesmerize-core` and `mamba update conda-forge mesmerize-core` and both times was told `All requested packages already installed`. 

I tried uninstalling `mamba uninstall mesmerize-core` (so I could then install anew in the environment), and got the following traceback (after it asked if I wanted to proceed):

>     Traceback (most recent call last):
>       File "C:\Users\Eric\miniconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 247, in remove
>         didx = self.item_index_map.pop(item)
>     KeyError: PackageRecord(_hash=8590190723005204531, name='__win', version='0', build='0', build_number=0, channel=Channel("@"), subdir='win-64', fn='__win', md5='12345678901234567890123456789012', package_type='virtual_system')
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Users\Eric\miniconda3\lib\site-packages\conda\exceptions.py", line 1118, in __call__
>         return func(*args, **kwargs)
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\mamba.py", line 936, in exception_converter
>         raise e
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\mamba.py", line 929, in exception_converter
>         exit_code = _wrapped_main(*args, **kwargs)
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\mamba.py", line 887, in _wrapped_main
>         result = do_call(parsed_args, p)
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\mamba.py", line 752, in do_call
>         exit_code = remove(args, parser)
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\mamba.py", line 240, in remove
>         conda_transaction = to_txn(
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\utils.py", line 436, in to_txn
>         final_precs = compute_final_precs(
>       File "C:\Users\Eric\miniconda3\lib\site-packages\mamba\utils.py", line 371, in compute_final_precs
>         final_precs.remove(i_rec)
>       File "C:\Users\Eric\miniconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 249, in remove
>         raise KeyError(item)
>     KeyError: PackageRecord(_hash=8590190723005204531, name='__win', version='0', build='0', build_number=0, channel=Channel("@"), subdir='win-64', fn='__win', md5='12345678901234567890123456789012', package_type='virtual_system')

For now I'll just create a new virtual environment, but just tagging this problem for now so we are aware of it.

**Comment by EricThomson** [comment]
Just noticed my silly mistake when updating I had left out the `-c` to set the channel parameter, when I fixed this it worked:
`mamba update -c conda-forge mesmerize-core`
