### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by rly** [nel-lab/mesmerize-core#231]
I followed the steps at the bottom of the README to install mesmerize and run the tests and got the following errors on my Mac M1. I suspect that these might be related to some update to numpy/scipy.

```
        # test to check get_rcm()
        cnmf_reconstructed_movie_AouterC = df.iloc[-1].cnmf.get_rcm("all")
        cnmf_reconstructed_movie_AouterC_actual = numpy.load(
            ground_truths_dir.joinpath("cnmf", "reconstructed_movie_new.npy")
        )
>       numpy.testing.assert_allclose(
            cnmf_reconstructed_movie_AouterC.as_numpy(),
            cnmf_reconstructed_movie_AouterC_actual, rtol=1e-1, atol=1e-10
        )

tests/test_core.py:555: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_allclose.<locals>.compare at 0x286c545e0>, array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0...        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]]))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=0.1, atol=1e-10', 'verbose': True}


    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError: 
E           Not equal to tolerance rtol=0.1, atol=1e-10
E           
E           Mismatched elements: 1 / 9600000 (1.04e-05%)
E           Max absolute difference: 0.00873967
E           Max relative difference: 0.14517041
E            x: array([[[0., 0., 0., ..., 0., 0., 0.],
E                   [0., 0., 0., ..., 0., 0., 0.],
E                   [0., 0., 0., ..., 0., 0., 0.],...
E            y: array([[[0., 0., 0., ..., 0., 0., 0.],
E                   [0., 0., 0., ..., 0., 0., 0.],
E                   [0., 0., 0., ..., 0., 0., 0.],...

/Users/rly/mambaforge/envs/mesmerize-core/lib/python3.10/contextlib.py:79: AssertionError
```

```
E           mesmerize_core.caiman_extensions._batch_exceptions.BatchItemUnsuccessfulError: Batch item was unsuccessful, traceback from subprocess:
E           Traceback (most recent call last):
E             File "/Users/rly/Documents/NWB/temp2/mesmerize-core/mesmerize_core/algorithms/cnmfe.py", line 89, in run_algo
E               cnm = cnm.fit(images)
E             File "/Users/rly/mambaforge/envs/mesmerize-core/lib/python3.10/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 594, in fit
E               self.estimates.sn, self.estimates.optional_outputs = run_CNMF_patches(
E             File "/Users/rly/mambaforge/envs/mesmerize-core/lib/python3.10/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 476, in run_CNMF_patches
E               B_tot = np.array(B_tot, dtype=np.float32)
E           TypeError: float() argument must be a string or a real number, not 'coo_matrix'

mesmerize_core/caiman_extensions/_utils.py:24: BatchItemUnsuccessfulError
```

```
========================================= short test summary info =========================================
FAILED tests/test_core.py::test_cnmf - AssertionError: 
FAILED tests/test_core.py::test_cnmfe - assert False is True
FAILED tests/test_core.py::test_cache - mesmerize_core.caiman_extensions._batch_exceptions.BatchItemUnsuccessfulError: Batch item was unsucces...
```

conda list:
```
# packages in environment at /Users/rly/mambaforge/envs/mesmerize-core:
#
# Name                    Version                   Build  Channel
absl-py                   2.0.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.6           py310hd125d64_1    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
anyio                     4.0.0              pyhd8ed1ab_0    conda-forge
aom                       3.6.1                hb765f3a_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h2aa6e3c_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.0              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
av                        10.0.0          py310hf6c82d4_3    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.6.3              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               hc338f07_0    conda-forge
bokeh                     3.2.2              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hb547adb_1    conda-forge
brotli-bin                1.1.0                hb547adb_1    conda-forge
brotli-python             1.1.0           py310h1253130_1    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.20.1               h93a5062_0    conda-forge
c-blosc2                  2.10.5               h8eb3132_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
caiman                    1.9.16          py310h1253130_0    conda-forge
cairo                     1.16.0            h1e71087_1016    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310hdcd7c05_0    conda-forge
charls                    2.4.2                h13dd4ca_0    conda-forge
charset-normalizer        3.3.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1           py310h38f39d4_1    conda-forge
cryptography              41.0.4          py310hdd3b5e7_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hb547adb_0    conda-forge
debugpy                   1.8.0           py310h1253130_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
ffmpeg                    6.0.0           gpl_h1ceb99f_105    conda-forge
flatbuffers               23.3.3               hb7217d7_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.43.1          py310hd125d64_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
frozenlist                1.4.0           py310h2aa6e3c_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.7.8                h9f1a10d_0    conda-forge
google-auth               2.23.2             pyhca7485f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
grpcio                    1.51.1          py310h63a0e3a_1    conda-forge
h5py                      3.9.0           nompi_py310h7fd3376_101    conda-forge
harfbuzz                  7.3.0                h46e5fef_0    conda-forge
hdf5                      1.14.1          nompi_h3aba7b3_100    conda-forge
hdmf                      3.10.0             pyh1ea47a8_0    conda-forge
holoviews                 1.17.1             pyhd8ed1ab_0    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.9.4        py310h6800ae8_0    conda-forge
imageio                   2.31.5             pyh8c1a49c_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.25.2             pyh1050b4e_0    conda-forge
ipyparallel               8.6.1              pyhd8ed1ab_0    conda-forge
ipython                   8.16.1             pyh31c8845_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.1.1              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jasper                    4.0.0                hff9eb24_1    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py310hbe9552e_3    conda-forge
jsonschema                4.19.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.19.1             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_bokeh             2.0.4              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.1              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.2           py310hbe9552e_0    conda-forge
jupyter_events            0.7.0              pyhd8ed1ab_2    conda-forge
jupyter_server            2.7.3              pyhd8ed1ab_1    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
keras                     2.11.0             pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5           py310h38f39d4_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
lame                      3.100             h1a8c8d9_1003    conda-forge
lazy_loader               0.3                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20220623.0      cxx17_h28b99d4_6    conda-forge
libaec                    1.1.2                h13dd4ca_1    conda-forge
libass                    0.17.1               h4da34ad_0    conda-forge
libavif16                 1.0.1                h18c541d_2    conda-forge
libblas                   3.9.0           18_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hb547adb_1    conda-forge
libbrotlidec              1.1.0                hb547adb_1    conda-forge
libbrotlienc              1.1.0                hb547adb_1    conda-forge
libcblas                  3.9.0           18_osxarm64_openblas    conda-forge
libcurl                   8.3.0                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libglib                   2.78.0               h24e9cb9_0    conda-forge
libgrpc                   1.51.1               hb15be72_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libidn2                   2.3.4                h1a8c8d9_0    conda-forge
libjpeg-turbo             2.1.5.1              hb547adb_1    conda-forge
liblapack                 3.9.0           18_osxarm64_openblas    conda-forge
liblapacke                3.9.0           18_osxarm64_openblas    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.24          openmp_hd76b1f2_0    conda-forge
libopencv                 4.8.0           py310hdc0018b_0    conda-forge
libopenvino               2023.0.1             h13dd4ca_3    conda-forge
libopenvino-arm-cpu-plugin 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-auto-batch-plugin 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-auto-plugin   2023.0.1             h13dd4ca_3    conda-forge
libopenvino-hetero-plugin 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-ir-frontend   2023.0.1             h13dd4ca_3    conda-forge
libopenvino-onnx-frontend 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-paddle-frontend 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-pytorch-frontend 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-tensorflow-frontend 2023.0.1             h13dd4ca_3    conda-forge
libopenvino-tensorflow-lite-frontend 2023.0.1             h13dd4ca_3    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libprotobuf               3.21.12              ha614eb4_2    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtasn1                  4.19.0               h1a8c8d9_0    conda-forge
libtiff                   4.5.1                h23a1a89_1    conda-forge
libunistring              0.9.10               h3422bc3_0    conda-forge
libvpx                    1.13.1               hb765f3a_0    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.5               he3bdae6_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
linkify-it-py             2.0.0              pyhd8ed1ab_0    conda-forge
llvm-openmp               17.0.2               h1c12783_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markdown                  3.5                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py310h2aa6e3c_1    conda-forge
matplotlib                3.8.0           py310hb6292c7_1    conda-forge
matplotlib-base           3.8.0           py310hd1c642d_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdit-py-plugins           0.4.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mesmerize-core            0.2.2                    pypi_0    pypi
mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
multidict                 6.0.4           py310h8e9501a_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy                      1.5.1           py310h2aa6e3c_1    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.9.2              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.9.2              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.9.2              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
nettle                    3.8.1                h63371fa_1    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  7.0.4              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numpy                     1.26.0          py310he2cad68_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
opencv                    4.8.0           py310hb6292c7_0    conda-forge
openh264                  2.3.1                hb7217d7_2    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.3                h53f4e23_0    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
p11-kit                   0.24.1               h29577a5_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.1           py310h5924a0a_1    conda-forge
pandoc                    3.1.3                hce30654_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     1.2.3              pyhd8ed1ab_0    conda-forge
param                     1.13.0             pyh1a96a4e_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
peakutils                 1.3.4              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0          py310h60ecbdf_0    conda-forge
pims                      0.6.1              pyhd8ed1ab_1    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h13dd4ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
protobuf                  4.21.12         py310h0f1eb42_0    conda-forge
psutil                    5.9.5           py310h2aa6e3c_1    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pugixml                   1.13                 h13dd4ca_1    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-opencv                 4.8.0           py310h69fb684_0    conda-forge
pyasn1                    0.5.0              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.3.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pynwb                     2.5.0              pyh267d04e_0    conda-forge
pyobjc-core               10.0            py310hd07e440_0    conda-forge
pyobjc-framework-cocoa    10.0            py310hd07e440_1    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqtgraph                 0.13.3             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.2              pyhd8ed1ab_0    conda-forge
python                    3.10.12         h01493a6_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.18.1             pyhd8ed1ab_0    conda-forge
python-flatbuffers        23.5.26            pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyviz_comms               3.0.0              pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py310h280b8fa_1    conda-forge
pyyaml                    6.0.1           py310h2aa6e3c_1    conda-forge
pyzmq                     25.1.1          py310h30b7201_1    conda-forge
qtconsole-base            5.4.4              pyha770c72_0    conda-forge
qtpy                      2.4.0              pyhd8ed1ab_0    conda-forge
rav1e                     0.6.6                h69fbcac_2    conda-forge
re2                       2023.02.01           hb7217d7_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.30.2             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.10.4          py310hd442715_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.35         py310h2aa6e3c_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h2aa6e3c_2    conda-forge
scikit-image              0.21.0          py310h1253130_0    conda-forge
scikit-learn              1.3.1           py310h417b086_1    conda-forge
scipy                     1.11.3          py310hd1cfc7d_1    conda-forge
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicerator                1.1.0              pyhd8ed1ab_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
svt-av1                   1.7.0                hb765f3a_0    conda-forge
tbb                       2021.10.0            h1995070_1    conda-forge
tensorboard               2.11.2             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.1           py310hfc83b78_4    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.11.1          cpu_py310ha244a38_0    conda-forge
tensorflow-base           2.11.1          cpu_py310hf369a12_0    conda-forge
tensorflow-estimator      2.11.1          cpu_py310h8d8d822_0    conda-forge
termcolor                 2.3.0              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tifffile                  2023.9.26          pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hb31c410_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py310h2aa6e3c_1    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.11.2             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uc-micro-py               1.0.1              pyhd8ed1ab_0    conda-forge
unicodedata2              15.1.0          py310h2aa6e3c_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.6              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.8              pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.6.4              pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.0              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.9              pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0          py310h2aa6e3c_1    conda-forge
x264                      1!164.3095           h57fd34a_2    conda-forge
x265                      3.5                  hbc6ce65_3    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2023.10.0          pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yarl                      1.9.2           py310hd125d64_1    conda-forge
z5py                      2.0.16          py310hd805275_1    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zfp                       1.0.0                h82938aa_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

**Comment by kushalkolar** [comment]
> Mismatched elements: 1 / 9600000 (1.04e-05%)

This is an extremely minor floating point diff. Probably due to slight differences in the M1 architecture vs. the architecture that the ground truths were made on.
