### ISSUE TITLE
mcorr_cnmf notebook running cnmf error

### ISSUE THREAD

**Issue by CharlotteWenxin** [nel-lab/mesmerize-core#302]
**Please be as descriptive as possible about your issue and provide all the information below. If you encounter an error please provide the full traceback, i.e. the  _entire_ error message etc. and screenshots.** Assistance is provided by the maintainers on a voluntary basis.

**Screenshots**
**Please include screenshots that describe the issue**.
![image](https://github.com/nel-lab/mesmerize-core/assets/157476627/04594e04-ff21-4534-acab-99bdfd35b716)

 - OS: Windows 11
 - mesmerize-core version: '0.4.0'
 - caiman version: ''1.11.1'
- Hardware description: 16 GPU

**Additional context**

Hello,

I'm running the mcorr_cnmf notebook with the demo data. When I tried to run index = -1  # most recently added item
df.iloc[index].caiman.run(): I got this in the output of the df.

'success': False,
 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\Zimmer_lab\\anaconda3\\envs\\mescore\\lib\\site-packages\\mesmerize_core\\algorithms\\cnmf.py", line 118, in run_algo\n    cnmf_hdf5_path = output_path.relative_to(output_dir.parent)\n  File "C:\\Users\\Zimmer_lab\\anaconda3\\envs\\mescore\\lib\\pathlib.py", line 818, in relative_to\n    raise ValueError("{!r} is not in the subpath of {!r}"\nValueError: \'C:\\\\Users\\\\Zimmer_lab\\\\caiman_data\\\\mesmerize-batch\\\\79f1619f-5b0a-4c51-a684-db2391c34a6b\\\\79f1619f-5b0a-4c51-a684-db2391c34a6b.hdf5\' is not in the subpath of \'\\\\Users\\\\Zimmer_lab\\\\caiman_data\\\\mesmerize-batch\' OR one path is relative and the other is absolute.\n'

Thank you very much for your help in advance.

**Comment by kushalkolar** [comment]
You're probably missing "C:` when you set the parent data path.

Also you can just do `df.iloc[ix].cnmf.get_output()` or `df.iloc[ix].mcorr.get_output()` and it will print the traceback nicely, it's not intended for users to manually dig into the output dict.

**Comment by CharlotteWenxin** [comment]
Thank you for your help!
