### ISSUE TITLE
caimanmanager install no longer working with SciPy 1.14

### ISSUE THREAD

**Issue by gusmihaian** [nel-lab/mesmerize-core#306]
When trying to install caimanmanager this is the error code I get:

```python
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mescore/bin/caimanmanager", line 7, in <module>
    from caiman.caimanmanager import main
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/__init__.py", line 4, in <module>
    from caiman.base.movies import movie, load, load_movie_chain, _load_behavior, play_movie
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/base/movies.py", line 36, in <module>
    import caiman.summary_images
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/summary_images.py", line 18, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/source_extraction/cnmf/__init__.py", line 4, in <module>
    from . import cnmf
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 30, in <module>
    from caiman.components_evaluation import estimate_components_quality
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/components_evaluation.py", line 8, in <module>
    import peakutils
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/peakutils/__init__.py", line 2, in <module>
    from .peak import *
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/peakutils/peak.py", line 7, in <module>
    from scipy.integrate import simps
ImportError: cannot import name 'simps' from 'scipy.integrate' (/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/scipy/integrate/__init__.py)
```

After posting the issue on SciPy they gave me this response:
integrate.simps was deprecated in favour of integrate.simpson as per the release notes https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations . Please raise this with the upstream package as this will need to be fixed at their end. In the meantime you can install a version of SciPy older than 1.14

**Comment by kushalkolar** [comment]
The last line shows this is an issue in peakutils, I would just use an older version of scipy:

````python
File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/peakutils/peak.py", line 7, in <module>
```
