### ISSUE TITLE
Does mesmerise-core work with 3D movies?

### ISSUE THREAD

**Issue by rajlakshmi-sawale** [nel-lab/mesmerize-core#312]
Hi, does mesmerise-core work with 3D movies? I tried to run it with my xyzt data but the mcorr failed. Any help would be appreciated!
Thanks!

**Comment by ethanbb** [comment]
Hi @rajlakshmi-sawale, is it failing at the local correlations step? If so, #300 is meant to address this, but it hasn't been merged yet.

**Comment by ethanbb** [comment]
OK I just merged that PR; can you try again after installing from the master branch? You will also need caiman version 1.11.2 or later.

**Comment by rajlakshmi-sawale** [comment]
> Hi @ethanbb, Thanks for the quick reply! 
I'm not sure where it is failing.. I have attached what I see.. Sorry, I might not be running it in the right way in the first place as I very new to this.
![image](https://github.com/user-attachments/assets/218a962b-4ce9-48d5-9116-a932639d800e)

**Comment by ethanbb** [comment]
Yup, that looks normal, it ran into an error while running but it didn't tell you exactly what it is. 

What does it show if you run `print(df.iloc[-1, :].outputs['traceback'])`?

**Comment by rajlakshmi-sawale** [comment]
This: ![image](https://github.com/user-attachments/assets/cf4be9a1-c2b7-48d1-b82f-d42a1c3f49aa)

**Comment by rajlakshmi-sawale** [comment]
To run it on 3D data, do we have to specify any additional parameters?
The only thing I changed so far in the provided notebook for 2D data was in this section:

`# We will start with one version of parameters
mcorr_params1 =\
{
  'main': # this key is necessary for specifying that these are the "main" params for the algorithm
    {
        'max_shifts': [5, 5, 2],
        'strides': [24, 24, 6],
        'overlaps': [12, 12, 2],
        'max_deviation_rigid': 3,
        'border_nan': 'copy',
        'pw_rigid': True,
        'gSig_filt': None
    },
}`

**Comment by ethanbb** [comment]
Oh ok you might need to use a different index than -1. If you just print the df you should be able to see which row corresponds to the failed run ("outputs" should be a dict with "success": False) and then you can use that index.

**Comment by rajlakshmi-sawale** [comment]
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\mesmerize_core\algorithms\mcorr.py", line 67, in run_algo
    mc.motion_correct(save_movie=True)
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 247, in motion_correct
    self.motion_correct_pwrigid(template=template, save_movie=save_movie)
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 349, in motion_correct_pwrigid
    self.motion_correct_rigid()
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 293, in motion_correct_rigid
    _fname_tot_rig, _total_template_rig, _templates_rig, _shifts_rig = motion_correct_batch_rigid(
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 2816, in motion_correct_batch_rigid
    m.motion_correct(max_shifts[1], max_shifts[0], template=None)[0])
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py", line 144, in motion_correct
    templ = submov.bin_median()                                        # create template with portion of movie
  File "C:\ProgramData\Anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py", line 274, in bin_median
    T, d1, d2 = np.shape(self)
ValueError: too many values to unpack (expected 3)`

**Comment by kushalkolar** [comment]
The traceback in the output doesn't have to be accessed manually, you can call get_output() and it will print the traceback nicely:

df.iloc[i].mcorr.get_output()

**Comment by ethanbb** [comment]
Ah, I think you also have to set  `is3D` to true in your params['main'].

**Comment by rajlakshmi-sawale** [comment]
Hi, I re-installed it and got this error: 
![image](https://github.com/user-attachments/assets/e910644c-17cc-4493-8a71-1b4f38fefc9e)

**Comment by kushalkolar** [comment]
Reload the dataframe from disk after running an item

**Comment by rajlakshmi-sawale** [comment]
![image](https://github.com/user-attachments/assets/31fb52ff-d363-43c2-94a2-adf7711cc983)

**Comment by kushalkolar** [comment]
The message says you're out of RAM. What are the dimensions of the movie? How many pixels do you have per neuron/ROI? What's your temporal sampling rate? Can you post a mean projectiom of some of the planes.

**Comment by rajlakshmi-sawale** [comment]
It is 259,1024,28 with 1200 frames at 2 volumes per second. The neurons are approx 100-130 pixels.
![MAX_avg](https://github.com/user-attachments/assets/e817ff44-50c5-497d-a6e6-93ef1017c9f6)

**Comment by kushalkolar** [comment]
How much RAM do you have

**Comment by rajlakshmi-sawale** [comment]
128 GB

**Comment by kushalkolar** [comment]
Only thing I can think of is to reduce the number of processes, unless
@ethanbb has any ideas. I've never done 3D mcorr or CNMF myself.

**Comment by ethanbb** [comment]
I agree, reduce number of processes by setting the `MESMERIZE_N_PROCESSES` environment variable. That way it will not try to process as many chunks at a time and will use less memory.

Also, maybe you already did this, but in `movies.py` the function `to3DFromPixelxTime` should look like this:

```python
def to3DFromPixelxTime(self, shape, order='F') -> 'movie':
    """
    Transform 2D movie (pixels x time) into 3D or 4D
    """
    return to_3D(self,shape[::-1],order=order).T
```

If not, you need to update your version of caiman.

**Comment by rajlakshmi-sawale** [comment]
Yes, the to3DFromPixelxTime function is as expected. After reducing the number of processes it gave this: 
![image](https://github.com/user-attachments/assets/e52609af-9cf0-4be4-92c2-00fbf144f031)

**Comment by ethanbb** [comment]
Oh interesting, I'm guessing I missed this because I only tried rigid 3d mcorr. Can take a look later today.

**Comment by ethanbb** [comment]
Yeah, sorry, the 3D mcorr PR had a bug which wasn't caught since I didn't add tests for both the rigid and piecewise cases.

Can you change line 115 of mesmerize_core/algorithms/mcorr.py from
```shifts += mc.z_shifts_els```
to
```shifts.append(mc.z_shifts_els)```
and see if it works now? If so I'll make a follow-up PR.

**Comment by rajlakshmi-sawale** [comment]
That worked! But now there seems to be some mismatch in dimensions for the visualisation..
![image](https://github.com/user-attachments/assets/6538d168-1f97-4713-92ae-6a74fd762446)

**Comment by kushalkolar** [comment]
Thanks for hanging in there! 
Mesmerize-viz is pinned to a much older fastplotlib that's quite limited, we don't have the resources right now to update mesmerize-viz. You'll have to get the latest release of fastplotlib and use the ImageWidget to view your results, it's just a few lines rather than a one-liner that mesviz provides. ImageWidget examples are here: https://github.com/fastplotlib/fastplotlib/blob/main/examples/notebooks/image_widget.ipynb

**Comment by rajlakshmi-sawale** [comment]
Okay, thanks!

**Comment by rajlakshmi-sawale** [comment]
Hi, the visualization worked. Thanks for creating this amazing tool! I am now trying to run the CNMF but got this error..   
![image](https://github.com/user-attachments/assets/bb942809-71ca-4ef6-b456-602a591f343a)
Any suggestions?

**Comment by ethanbb** [comment]
Glad you're making progress! I believe this error is because you need to provide gSig as a 3-element list for 3D CNMF. The same is true for rf and stride in the patch group, if you're using patches. And finally you will have to disable the CNN by setting use_cnn in the quality group to False.

**Comment by rajlakshmi-sawale** [comment]
What about thid? 
![image](https://github.com/user-attachments/assets/5e0bd0c7-32e7-45fb-8837-1e9a0eaff19e)

**Comment by ethanbb** [comment]
I'm not sure, I haven't run into that one. It looks like at least one of the patch runs is giving an S of None when that's not expected. My guess would be that some of your patches are invalid in some way (empty?) and that tweaking your patch settings may fix it (but this is still a bug in caiman, probably).
