### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by CeeLo** [nel-lab/mesmerize-core#313]
Hi, I've been having issues with installing Mesmerize-core. I have been following the instructions from the mesmerize-core to run the following: mamba create -n mescore -c conda-forge mesmerize-core and attempted to reinstall anaconda to see if it fixes the issue, but it did not do anything so far.

My computer information is:
Operating System: MacOS Sonoma 14.5
Hardware Type: M1 chip, 16 GB RAM
Python: 3.10.13

I have been getting the error message listed below. I'm not sure what the exact issue is in this case, I saw that there were issues with installing individual packages as well. Do you have any advice on how to troubleshoot this? 

Error Message:
Traceback (most recent call last):
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in call
return func(*args, **kwargs)
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
raise e
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
exit_code = _wrapped_main(*args, **kwargs)
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
result = do_call(parsed_args, p)
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
exit_code = create(args, parser)
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
return install(args, parser, "create")
File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 558, in install
transaction.fetch_extract_packages()
RuntimeError: Found incorrect download: libexpat. Aborting

$ /Users/cynthialo/anaconda3/bin/mamba create -n mescore -c conda-forge mesmerize-core

environment variables:
CIO_TEST=
CONDA_ALLOW_SOFTLINKS=false
CONDA_DEFAULT_ENV=base
CONDA_EXE=/Users/cynthialo/anaconda3/bin/conda
CONDA_PREFIX=/Users/cynthialo/anaconda3
CONDA_PROMPT_MODIFIER=(base)
CONDA_PYTHON_EXE=/Users/cynthialo/anaconda3/bin/python
CONDA_ROOT=/Users/cynthialo/anaconda3
CONDA_SHLVL=1
CURL_CA_BUNDLE=
INFOPATH=/opt/homebrew/share/info:
LD_PRELOAD=
MANPATH=/opt/homebrew/share/man::
PATH=/Users/cynthialo/anaconda3/bin:/Users/cynthialo/anaconda3/condabin:/op
t/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App
/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cry
ptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security
.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.c
ryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Lib
rary/Apple/usr/bin
REQUESTS_CA_BUNDLE=
SSL_CERT_FILE=

 active environment : base
active env location : /Users/cynthialo/anaconda3
        shell level : 1
   user config file : /Users/cynthialo/.condarc
populated config files : /Users/cynthialo/.condarc
conda version : 24.7.1
conda-build version : 24.5.1
python version : 3.10.13.final.0
solver : classic
virtual packages : __archspec=1=m1
__conda=24.7.1=0
__osx=14.5=0
__unix=0=0
base environment : /Users/cynthialo/anaconda3 (writable)
conda av data dir : /Users/cynthialo/anaconda3/etc/conda
conda av metadata url : None
channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
https://conda.anaconda.org/conda-forge/noarch
https://conda.anaconda.org/bioconda/osx-arm64
https://conda.anaconda.org/bioconda/noarch
https://repo.anaconda.com/pkgs/main/osx-arm64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/osx-arm64
https://repo.anaconda.com/pkgs/r/noarch
package cache : /Users/cynthialo/anaconda3/pkgs
/Users/cynthialo/.conda/pkgs
envs directories : /Users/cynthialo/anaconda3/envs
/Users/cynthialo/.conda/envs
platform : osx-arm64
user-agent : conda/24.7.1 requests/2.32.3 CPython/3.10.13 Darwin/23.5.0 OSX/14.5
UID:GID : 501:20
netrc file : None
offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install

**Comment by kushalkolar** [comment]
@ethanbb @pgunn I don't use conda, any ideas?

**Comment by ethanbb** [comment]
This seems not specific to mesmerize-core...are you able to install anything? For example can you run `mamba create -n numpy -c conda-forge numpy`?

**Comment by pgunn** [comment]
Also try a `conda clean --all`

**Comment by pgunn** [comment]
I'm currently on vacation, but if you like when I get back (on the 4th) we can do a VC and see if we can figure it out live. Unless someone else solves it first.

One not of info you can add to this ticket that may let me solve it earlier would be to do a "conda env list" and paste the results in here; I have a few hunches that might explain it but we need more info

**Comment by CeeLo** [comment]
Thank you so much for your help! I think I managed to fix the mamba issue, as I've been able now to create the environment without any issues, but the verification step has not been working for me (mesmerize_core.__version__), it says it is not found. If you are able to jump on a VC after your vacation, I would really appreciate the help in getting mesmerize running on my computer! 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 3
      1 import mesmerize_core
      2 print('import')
----> 3 mesmerize_core._version_

AttributeError: module 'mesmerize_core' has no attribute '_version_'

**Comment by CeeLo** [comment]
And here is the conda env list:

# conda environments:
#
                         /Users/cynthialo/Library/Caches/org.R-project.R/R/basilisk/1.12.1/0
                         /Users/cynthialo/Library/Caches/org.R-project.R/R/basilisk/1.12.1/zellkonverter/1.10.1/zellkonverterAnnDataEnv-0.8.0
base                  *  /opt/anaconda3
mescore                  /opt/anaconda3/envs/mescore

**Comment by pgunn** [comment]
@CeeLo It may be that the formatting that github does is making those instructions less clear (or perhaps our communcation about them).

`__version__` is meant to have double-underscores on both sides (github tends to format that with italics or bold I think). Can you check to see if `mezmerize_core.__version__` has a value?

**Comment by CeeLo** [comment]
Oh yes, it does! Thank you, it says 0.4.0. Just one last question, I am trying to run through the example notebook, but it wasn't quite clear to me where to get/use the example data - does the download_demo() function download it, or am I missing a download somewhere?

**Comment by kushalkolar** [comment]
Yes that function downloads the demo movie if you've run the caimanmanager
step.
